'use strict';

const config = internalBinding('config');
const {
  LTTNG_HTTP_CLIENT_REQUEST = () => {},
  LTTNG_HTTP_CLIENT_RESPONSE = () => {},
  LTTNG_HTTP_SERVER_REQUEST = () => {},
  LTTNG_HTTP_SERVER_RESPONSE = () => {},
  LTTNG_NET_SERVER_CONNECTION = () => {},
  LTTNG_NODE_GLOBAL_ENTRY = () => {},
  LTTNG_NODE_GLOBAL_EXIT = () => {},
  LTTNG_NET_STREAM_END = () => {}
} = (config.hasLTTNG? internalBinding('lttng') : {});

module.exports = {
  LTTNG_HTTP_CLIENT_REQUEST,
  LTTNG_HTTP_CLIENT_RESPONSE,
  LTTNG_HTTP_SERVER_REQUEST,
  LTTNG_HTTP_SERVER_RESPONSE,
  LTTNG_NET_SERVER_CONNECTION,
  LTTNG_NODE_GLOBAL_ENTRY,
  LTTNG_NODE_GLOBAL_EXIT,
  LTTNG_NET_STREAM_END
};
